apiVersion: v1
kind: Service
metadata:
  name: user-service-lb
spec:
  selector:
    app: user-service    # Ye wahi label hai jo Deployment mein tha
  ports:
    - protocol: TCP
      port: 80           # Bahar se is port pe request aayegi
      targetPort: 5001   # Ye request pod ke 5001 port pe jayegi
  type: LoadBalancer     # Ye port ko expose karne mein madad karta hai